version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - pip install pytest
  build:
    commands:
      - pytest test.py > result.log
      - echo "✅ Test finalizado correctamente"
artifacts:
  files:
    - result.log
